### ISSUE TITLE
with gear 360 (2016)

### ISSUE THREAD

**Issue by salotime** [ilker-aktuna/Gear-360-File-Access-from-Android-phones#1]
I'm pretty sure I'm doing correctly the procedure as it is written, trying with my gear 360 2016. 
When I put on the Sd Card in  the camera and turn it on it goes in a hardware test mode. After few seconds the blue light comes on but not the green one. I suppose it doesn't create the server

**Comment by ilker-aktuna** [comment]
I'm sorry I don't have a Gear 360 2016 version to test with.
Probably it won't work if it goes into a test mode.
sorry...

**Comment by salotime** [comment]
No problem, I guess I'll do all the post processing with the pc. Just to
let you know that it doesn't work

Il Mar 27 Lug 2021, 23:06 ilker Aktuna ***@***.***> ha
scritto:

**Comment by ilker-aktuna** [comment]
thanks for the feedback. I'll update my README.
