### ISSUE TITLE
With V1 folder on SD card I was able to connect and see files however after clicking "Download" there is "Downloading..." message but nothing is downloaded. "Local Files" section is empty.

### ISSUE THREAD

**Issue by xde** [ilker-aktuna/Gear-360-File-Access-from-Android-phones#2]
With folder V1 on SD card it's connected properly. I see files but when I press "Download" only message "Downloading" appears and then nothing.
"Local Files" section is empty even after refresh.
Can't find files also on my phone.
I don't have SD card on phone, only phone memory. Xiaomi phone.
Also there is no "Gear260 folder". Gear 360 folder in DCIM is there but without downloaded files.

**Comment by ilker-aktuna** [comment]
You have to accept permissions requested by the application. Specifically storage permission.
If you accept it, downloaded files will be available under DCIM/Gear360 folder on your SD card.

**Comment by xde** [comment]
Yes, this is obvious. I have accepted and also checked twice in settings if there is storage permission allowed for this app.
"under DCIM/Gear360 folder on your SD card"- As I wrote, I don't have sdcard on my phone, only phone memory.

**Comment by ilker-aktuna** [comment]
IF you don't have SD card on the phone , then it should point to DCIM/Gear360 directly under internal memory.
What do you see on your phone screen , on the app ?

**Comment by xde** [comment]
It doesn't point apparently :( 
Something like this: https://imgur.com/a/3BwTJlR
Is code for mobile app also on github?
Is there any other solution which I can use to transfer data on mobile phone?
"Samsung Gear 360 Manager for all devices" doesn't work properly.

**Comment by ilker-aktuna** [comment]
I will create a test version for you to test and log what is happening. Can you collect logcat if I send you a debug version ?

**Comment by xde** [comment]
Sure, I can do that. 
First maybe try to remove sd card on your phone and check if bug is present there also.

**Comment by ilker-aktuna** [comment]
I am not using an SD card. When replying to you I wrote SD card because default path of DCIM is selected on the OS (Android) according to wether you have an SD card or not.
So on my experience, without an SD card , the app can write the images on path DCIM/Gear360

if you are willing to test a debug version, I can put some logging to see what is wrong with your setup.

**Comment by ilker-aktuna** [comment]
I can add you as a closed alpha tester for debug version. Can you provide your email address that you use on Google Play ?

**Comment by ilker-aktuna** [comment]
Hi,

If you still have this problem, can you please download the files on Github again and replace the files on your Gear 360 device and then try again ?
Please let me know if it works for you after this change.

Thanks.

**Comment by xde** [comment]
Same after latest change (tested V2 and V1 both), can't download image

**Comment by ilker-aktuna** [comment]
OK. I made some changes on the Github files yesterday.
After that change I received positive results from 2 users who had similar issue.
So please;

1.	Uninstall the app on your Android phone
2.	Delete the mod files on your Gear 360
3.	Download files again from Github and put them on the Gear 360 device
4.	Re-install the app on your Android phone
5.	Allow all requested permissions by the app
Now it should work.

Thanks,

**Comment by xde** [comment]
Yes, I've tested already after the change and with deleted files on gear 360. Reinstalled also Android App and again allowed permission. Today I've tried this again as with above steps. 
Same outcome.
Maybe some phone specific issue.

**Comment by ilker-aktuna** [comment]
can you send a screenshot from the app screen ?

**Comment by xde** [comment]
I've posted already screenshot above: https://imgur.com/a/3BwTJlR
Same after latest changes: https://imgur.com/a/ihInPI3

**Comment by ilker-aktuna** [comment]
well that's really interesting. you have downloaded the recent files from Github and you still can not download.
can you try on another phone ?
I know it is frustrating but the recent fix really addressed all issues. if you still have the issue, I need logs from your phone.
